### ISSUE TITLE
Support very large classes

### ISSUE THREAD

**Issue by KN4CK3R** [ReClassNET/ReClass.NET#148]
Very large classes lead to huge file loading times and a broken vertical scroll bar.

See #147

**Comment by Timboy67678** [comment]
we could do something where if the node count is higher than a certain threshold, offer to remove unused nodes, otherwise add a load dialog (or status progress like with debug symbols)

narrowed it down to the CreateNodeFromElement function in the dxchg ReClassNetFile.Read

![image](https://user-images.githubusercontent.com/994534/74805713-b09f0000-532f-11ea-81a7-585a18561295.png)
