### ISSUE TITLE
i want to find all memory strings by defining the length of the string

### ISSUE THREAD

**Issue by Charltsing** [ReClassNET/ReClass.NET#160]
I want to find all memory strings by defining the length of the string
For example, a 16-character lowercase string or 32-character number + letter string 

Can you provide this function ？
or
Do you know of any tools that provide this functions？

**Comment by GH-Rake** [comment]
Cheat Engine can do this

**Comment by Charltsing** [comment]
> Cheat Engine can do this

Do you tell me how to do?   I did not find a function to search for strings based on length and character type in CE.
thinks a lot

**Comment by GH-Rake** [comment]
Your needs are too specific for Cheat Engine

Use this code to learn how to find all strings: https://github.com/glmcdona/strings2

Loop through them all

checking string length is easy, strlen() or std::string::length()

Use [std::isupper](https://en.cppreference.com/w/cpp/string/byte/isupper) to check if uppercase

Use std::isdigit() to check if it's a number

You will have to code a custom solution using the above information

**Comment by Charltsing** [comment]
thank you for your replay!

i don't understand how to use cpp programming...

so I hope this tool can develop this function.

I will learn string2, thank you!

**Comment by KN4CK3R** [comment]
I'm thinking about a regex search which could handle this case too. But it will take some time to implement.

**Comment by KN4CK3R** [comment]
I have implemented a regex search method. You can now search for regular expressions:
![grafik](https://user-images.githubusercontent.com/1666336/86539604-321db600-befe-11ea-93ca-48cbd9d0e27f.png)

Be aware that this searches for matching substrings because there is no way to know where a string begins and ends (string may have a `\0` suffix, string may have a length prefix, ...). So if you search for a 7 character long string you may get not only the results you are expecting:
![grafik](https://user-images.githubusercontent.com/1666336/86539644-8a54b800-befe-11ea-8854-c947d7f4c8cd.png)

For your original request you can use `[a-z0-9]{10}` if you search for a 10 character string with "normal" characters.

**Comment by Charltsing** [comment]
good job!
