### ISSUE TITLE
ReClass broke down

### ISSUE THREAD

**Issue by shert391** [ReClassNET/ReClass.NET#245]
Good afternoon. People, I have ReClass does not show some addressed data after downloading . rcnet project. Who knows how to solve the problem?

![x32dbg_bX0c33UR90](https://user-images.githubusercontent.com/96663754/208160109-59168423-8a82-4a57-a478-c7b43f588bfd.png)

**Comment by KN4CK3R** [comment]
Just a guess... The `ArrayPlayerData` instance is 336 bytes big. So ReClass tries to read 336 bytes from 0131FF18. If this overlaps a memory section (or protection) boundary, the read fails and zero'ed bytes are displayed. You can see the read failed because on the left side the error icon is displayed. If you change the `players[64]` to maybe 10 it may work.

**Comment by shert391** [comment]
> 

Good afternoon. 
I reduced the size of the array and it worked for me!
Thank you for answering!
