### ISSUE TITLE
Cant open the game ROS.EXE (Rules of survival)

### ISSUE THREAD

**Issue by ori1337** [ReClassNET/ReClass.NET#49]
First hello, and i have to tell you that i love this project 

2nt why i cant open this process, i didnt compile right ?

i mean i cant compile the project "NativeCore.Unix"
I mean i have problems when i try to compile it 
but i dont care its Unix i use windogayos(jk windows)

i really wanna find some cool pointers on this reclassers Becuase this reclasser is so much sexy and good and made in germny XDD 

Thank you for the Software, and pleaseee Help i cant find the game :9

**Comment by I-MrFixIt-I** [comment]
I‘m not sure whether I understood you correctly. But if you have problems with the Unix project, simply remove it from the solution (click the project and press delete). After that you should be able to build all projects. If not, you are still missing something.

When I started I had to remove the project aswell retargeting the native solution(s). The second step was necessary because I only had a newer version of (windows 10 sdk) installed.

**Comment by KN4CK3R** [comment]
ROS may have an anti cheat system which prevents to open the process. There is nothing ReClass.NET can do about it. You need to disable the anti cheat. I'm sure the plugin https://github.com/ReClassNET/ReClass.NET-HandleAbuser may help too.
